spring.cloud.config.server.git.uri: file://${user.home}/Work/training/microservice-online-training/training/centralized-config/config-repo
# spring.cloud.config.server.git.uri: https://github.com/microservice-in-action/config-repo
#spring.cloud.config.server.git.uri: http://localhost:8000
# spring:
#   cloud:
#     config:
#       server:
#         git:
#           uri: file://${user.home}/Work/training/microservice-online-training/training/centralized-config/config-repo

server:
  port: 8888
